<?php
namespace bizySoft\bizyStore\model\core;

/**
 * SequenceSchema holds the sequence information for the table based on dbId.
 *
 * Sequences in general are columns that have their values generated by the database and are guaranteed to be unique and not null
 * within a table. bizyStore supports multiple sequenced columns per table, the database vendor implementation may or may not 
 * allow multiple sequenced columns.
 * 
 * <span style="color:orange">If you find our software helpful, the best way to contribute
 * is to hire us to work for you. </span> Details at <a href="http://www.bizysoft.com.au">http://www.bizysoft.com.au</a>
 *
 * @author Chris Maude, chris@bizysoft.com.au
 * @copyright Copyright (c) 2016, bizySoft
 * @license http://www.bizysoft.com.au/LICENSE.html GNU GPL. See the LICENSE file with this distribution.
 */
class SequenceSchema extends Schema
{
	/**
	 * SequenceSchema instances are constructed under controlled conditions from the generated Model classes.
	 * 
	 * @param array $columnData
	 */
	public function __construct($sequenceData)
	{
		parent::__construct($sequenceData);
	}
		
	/**
	 * Is the property part of the sequence schema for the database.
	 * 
	 * @return bool
	 * 
	 * @param string $dbId
	 * @param string $property
	 */
	public function is($dbId, $property)
	{
		if (isset($this->schema[$dbId]))
		{
			/*
			 * Use array_key_exists here as most databases will have a null sequence name.
			 */
			return array_key_exists($property, $this->schema[$dbId]);
		}
		return false;
	}
}
?>
